export type {
  InstagramFeedProviderId,
  InstagramMediaItem,
  InstagramMediaType,
  InstagramProfileSummary,
} from "./types";
export {
  ELFSIGHT_PLATFORM_SCRIPT,
  ELFSIGHT_WIDGET_CLASS,
  getInstagramFeedProvider,
  STOREFRONT_INSTAGRAM_AVATAR_SRC,
  STOREFRONT_INSTAGRAM_DISPLAY_NAME,
  STOREFRONT_INSTAGRAM_FOLLOWERS_COUNT_LABEL,
  STOREFRONT_INSTAGRAM_HANDLE,
  STOREFRONT_INSTAGRAM_HERO_IMAGE,
  STOREFRONT_INSTAGRAM_POSTS_COUNT_LABEL,
  STOREFRONT_INSTAGRAM_URL,
  STOREFRONT_PREVIEW_TILE_OBJECT_POSITIONS,
} from "./config";
